<?php
use \Drupal\user\UserInterface;

/**
* Implementation of hook_theme()
*/
function crm_integration_theme($existing, $type, $theme, $path) {
  return [
    'form_settings' => [
      'variables' => [
        'form' => null, 
        'auth_url' => null 
      ]
    ],
  ];
}

/**
* Implementation of hook_ENTITY_TYPE_insert()
*/
function crm_integration_user_insert(UserInterface $user) {
  $config = \Drupal::config('crm_integration.settings');
  $roles_config = $config->get('roles');
  
  $roles = $user->getRoles();
  $data = [
    'name' => $user->getDisplayName(),
    'email' => $user->getEmail(),
  ];
  // validate role user
  $rol = array_intersect($roles_config, $roles);
  if($rol) {
    $service = \Drupal::service('crm_integration.api_service');
    $createUser = $service->createUse($data);
  }
}
