crm.settings:
  type: config_object
  label: 'CRM settings'
  mapping:
    client_id:
      type: string
      label: 'Client ID'
    client_secret:
      type: string
      label: 'Client Secret'
    domain:
      type: string
      label: 'Bigin Domain'